### ISSUE TITLE
alias-model-in-controller to restrictive?

### ISSUE THREAD

**Issue by miguelcobain** [netguru/eslint-plugin-ember#75]
I just started using eslint-plugin-ember. One thing I noticed is that i get a lot of `alias-model-in-controller` errors. The rule makes sense, but some times we have routes where we're not interested in the model. e.g a login route or a forgot password route.
I wonder if we have any alternative. Maybe detect if the model hook was implemented or not?

**Comment by scottkidder** [comment]
We've run into the same thing. I think that although it would be nice, that type of check is out of the scope of linting.

As a solution for this and another issue we've considered creating a set of blueprints that:

1. Follow rules so that a freshly generated file does not have lint failures.
2. Optionally? include an eslint disable for certain rules like `alias-model-in-controller`

**Comment by michalsnik** [comment]
Hey @miguelcobain, I don't think we can check in controller if model hook is implemented on corresponding route, unfortunately..

All of those rules are not mandatory however. You can always disable any rule in `.eslintrc` or per file using `/* eslint-disable ember/alias-model-in-controller */`. I don't see any better solution to this problem at this moment.

@scottkidder Blueprints' topic is something I'd rather keep it in another issue as proposal to consider :)

**Comment by miguelcobain** [comment]
Absolutely. What I did was to disable it globally. But I can imagine a good workflow to disable it on a controller by controller basis.

Feel free to close this issue if no further action is required.
